[package]
name = "etcd-rs"
version = "0.2.0-alpha.4"
authors = ["ccc13 <currantxx@gmail.com>"]
edition = "2018"
keywords = ["etcd", "future"]
repository = "https://github.com/ccc13/etcd-rs"
homepage = "https://github.com/ccc13/etcd-rs"
description = "etcd client for rust"
documentation = "https://docs.rs/etcd-rs"
license = "MIT"

[dependencies]
tonic = "0.1.0-alpha.6" 
bytes = "0.4"
prost = "0.5"
prost-derive = "0.5"
tokio = "0.2.0-alpha.6"
async-stream = "0.1.2"

[dev-dependencies]

[build-dependencies.tonic-build]
version = "0.1.0-alpha.6"
default-features = false
features = ["transport"]