[package]
name = "etcd-rs"
version = "0.1.4"
authors = ["ccc13 <currantxx@gmail.com>"]
edition = "2018"
keywords = ["etcd", "future"]
repository = "https://github.com/ccc13/etcd-rs"
homepage = "https://github.com/ccc13/etcd-rs"
description = "etcd client for rust"
documentation = "https://docs.rs/etcd-rs"
license = "MIT"
build = "build.rs"

[package.metadata.docs.rs]
all-features = true

[dependencies]
grpcio = "0.4"
futures = "0.1"
protobuf = { version = "2", features = ["with-bytes"] }
tokio-timer = "0.2"

[dev-dependencies]
tokio = "0.1"

[build-dependencies]
protoc-grpcio = "1.1"
